export class Consulationview {
    consulation_id:number;
    meeting_id:number;
    counselor_id:number;
    counselor_title:string;
    counselor_name:string;
    counselor_middlename:string;
    counselor_surname:string;
    counselortype_id:number;
    counselortype_name:string;
    partylist_id:number;
    partylist_name:string;
    counselordivision_id:number;
    counselordivision_name:string;
    count_consulationdetail:number;
    create_date:Date;
    create_by:number;
    create_title:string;
    create_name:string;
    create_surname:string;
    update_date:Date;
    update_by:number;
    update_title:string;
    update_name:string;
    update_surname:string;
}
