export class Consulationdetailview {
    consulationdetail_id:number;
    consulation_id:number;
    meeting_id:number;
    topictype_id:number;
    topictype_name:string;
    objective_id:number;
    objective_name:string;
    consulationdetail_topic:string;
    consulationdetail_detail:string;
    consulation_attachment_flag:number;
    status_id:number;
    status_name:string;
    create_date:Date;
    create_by:number;
    update_date:Date;
    update_by:number;
    send_date:Date;
    send_by:number;
    receive_date:Date;
    receive_by:number;
}
