export class Meetingview {
    meeting_id:number;
    meeting_date:Date;
    meetingtype_id:number;
    meetingtype_name:string;
    meetingterm_id:number;
    meetingterm_name:string;
    meetingset_id:number;
    meetingset_desc:string;
    meeting_year:number;
    meeting_time:number;
    count_consulation:number;
    count_consulationtotal:number;
    create_date:Date;
    create_by:number;
    create_title:string;
    create_name:string;
    create_surname:string;
    update_date:Date;
    update_by:number;
    update_title:string;
    update_name:string;
    update_surname:string;   
}
