export class Userprofileview {
    user_id:number;
    user_cid:string;
    user_login:string;
    user_password:string;
    user_title:string;
    user_name:string;
    user_midname:string;
    user_surname:string;
    user_position:string;
    userlevel_id:number;
    userlevel_name:string;
    costcenter_id:number;
    costcenter_name:string;
    usertype_id:number;
    usertype_name:string;
    user_status:number;
    user_email:string;
    user_member:number;
    user_ministry:number;
}
